### ISSUE TITLE
launcher fails to extract update on mac (update error)

### ISSUE THREAD

**Issue by ethanboyethan1** [minecraft-linux/mcpelauncher-manifest#1176]
**the bug:**
tried to install the new update for the launcher, and then _"fails to extract"_ the update

**steps to reproduce:**
1. open the launcher
2. immediately see that there's a _"New version of Minecraft Bedrock Launcher is available!"_
3. install the update
4. see the error

**what i've tried:**
1. reinstalling
2. went into dev mode
3. searching for issues that relate to this bug

**what i expect:**
to just install the new update normally

**the screenshot:**

![Image](https://github.com/user-attachments/assets/9e402d8a-84bf-41d3-9c60-dc18f849a2b7)

**laptop (2019 intel macbook pro) info:**
 - OS: [macOS Sequoia Beta 15.6]
 - Version [Minecraft_Bedrock_Launcher_v0.19.0-macOS-x86_64-0.2.510_macOS_10.13.0.dmg (0.2.510)]
 - Installation Type [.dmg]

**Comment by ethanboyethan1** [comment]
currently aware that this happens with every mac so far. thought it was just me

**Comment by ethanboyethan1** [comment]
fixed, had to use the latest stable github actions build for macOS

https://github.com/minecraft-linux/macos-builder/actions/runs/15788163018

**Comment by Luke110472** [comment]
Unfortunately, it's still not working. I have exactly the same problem.

**Comment by Luke110472** [comment]
> Unfortunately, it's still not working. I have exactly the same problem.

macOS Sequoia 15.5
