### ISSUE TITLE
Could not select custom skin

### ISSUE THREAD

**Issue by MCPE-PC** [minecraft-linux/mcpelauncher-manifest#53]
I can select a skin file, but the game says the selected file is not an image file.

 * OS: `Linux mcpe-pc-laptop 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
 * Have `zenity` installed
 * Skin file name is `skin.png`
 * Skin uses Alex slim model

**Comment by Mhowser** [comment]
Try using the Steve model instead if you can. You should have an option to
switch between both models in the client.

**Comment by MCPE-PC** [comment]
Original Steve skin also.

**Comment by MCPE-PC** [comment]
Fixed after purging config

**Comment by evelire** [comment]
@MCPE-PC Hello, what config did you delete? I think I have the same problem, just can't import any custom skin
![Снимок экрана от 2020-03-20 13-27-48](https://user-images.githubusercontent.com/60151750/77157329-2bd00f00-6ab2-11ea-9baf-03552b93e7c0.png)

**Comment by Mhowser** [comment]
Do you have Zenity installed?

**Comment by evelire** [comment]
@Mhowser yeah, latest version (3.28.1-1). I choose a skin through such a window
![Снимок экрана от 2020-03-20 22-31-40](https://user-images.githubusercontent.com/60151750/77199913-ab81cc00-6afa-11ea-8400-fe01eda023a0.png)

**Comment by evelire** [comment]
**FIXED**

the mistake was that the path to the skin had Russian characters. I moved the skin to my home folder and it worked

**Comment by ghost** [comment]
this is still a bug and still occurs with file paths that have special characters
so i think this should be reopend
